# Generated by Django 5.1.3 on 2024-12-02 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_venta', models.FloatField()),
                ('tiempo_fabricacion', models.PositiveIntegerField()),
                ('caducidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_destino', to='Route_Generator.ciudad')),
                ('ciudad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_origen', to='Route_Generator.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('cliente_id', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Route_Generator.ciudad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Route_Generator.producto')),
            ],
        ),
    ]
